### PR TITLE
Typo with phpunit PHP command

### PR DESCRIPTION
**Pull request by pierregaste**

### CODE REVIEW

**Comment by bocharsky-bw** [comment]
Good catch! Thank you @pierregaste 

Deployed!

**Comment by bocharsky-bw** [comment]
Hey @pierregaste ,

Oh, I see the same misprint in further chapters... I think it could be done with an auto-replacement feature at a time in any editor/IDE. Would you like to open a PR to fix other misprints? If not - never mind, just let me know and I will do it by myself

Cheers!

**Comment by pierregaste** [comment]
@bocharsky-bw You're right! It will be more easier like this :)
It's done here: https://github.com/knpuniversity/symfony2-rest/pull/12

**Comment by bocharsky-bw** [comment]
Sweeeet!

**Pull request merged**
